name: mineral_mongodb
description: The mongoDB module was designed exclusively for the Mineral framework, it allows you to communicate with a MongoDB database.
version: 1.0.1

repository: https://github.com/mineral-dart/mongodb
# homepage: https://www.example.com

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.17.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  mineral_ioc: ^1.0.0
  mongo_dart: ^0.7.4+1
  uuid: ^3.0.6
